name: Documentation

on:
  push:
    branches:
      - branch_for_wiki
    paths:
      - "wiki_docs/**"
  repository_dispatch:
    types: [wiki_docs]
  workflow_dispatch:
  gollum:

env:
  GIT_AUTHOR_NAME: Actionbot
  GIT_AUTHOR_EMAIL: actions@github.com

jobs:
  job-sync-docs-to-wiki:
    runs-on: ubuntu-latest
    if: github.event_name != 'gollum'
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Sync docs to wiki
        uses: newrelic/wiki-sync-action@main
        with:
          source: wiki_docs
          destination: wiki  # wiki repo
          token: ${{ secrets.TOKEN_FOR_WIKI }}
          gitAuthorName: ${{ env.GIT_AUTHOR_NAME }}
          gitAuthorEmail: ${{ env.GIT_AUTHOR_EMAIL }}
  
  job-sync-wiki-to-docs:
    runs-on: ubuntu-latest
    if: github.event_name == 'gollum'
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.TOKEN_FOR_WIKI }} # allows us to push back to repo
          ref: branch_for_wiki
      - name: Sync Wiki to Docs
        uses: newrelic/wiki-sync-action@main
        with:
          source: wiki
          destination: wiki_docs
          token: ${{ secrets.TOKEN_FOR_WIKI }}
          gitAuthorName: ${{ env.GIT_AUTHOR_NAME }}
          gitAuthorEmail: ${{ env.GIT_AUTHOR_EMAIL }}
          branch: branch_for_wiki
