name: Test branch

on:
  repository_dispatch:
    types: [wiki_docs]
  workflow_dispatch:

env:
  GIT_AUTHOR_NAME: Actionbot
  GIT_AUTHOR_EMAIL: actions@github.com

jobs:
  job-test:
    runs-on: ubuntu-latest
    steps:
      - name: Test
        uses: actions/checkout@v2
      - run: echo "The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "${{ github.head_ref }}"
      - run: echo "${{ github.ref##*/ }}"
      - run: echo "${{ github.workflow_ref }}"
